#!/bin/sh
set -e

# Set current timestamp as commit hash env variable
LHCI_BUILD_CONTEXT__CURRENT_HASH="${LHCI_BUILD_CONTEXT__CURRENT_HASH:-$(node -p "new Date().getTime().toString(16).split('').reverse().join('')")}"
export LHCI_BUILD_CONTEXT__CURRENT_HASH

LHCI_BUILD_CONTEXT__CURRENT_BRANCH="${LHCI_BUILD_CONTEXT__CURRENT_BRANCH:-main}"
export LHCI_BUILD_CONTEXT__CURRENT_BRANCH

LHCI_BUILD_CONTEXT__COMMIT_MESSAGE="${LHCI_BUILD_CONTEXT__COMMIT_MESSAGE:-CRON_RUN}"
export LHCI_BUILD_CONTEXT__COMMIT_MESSAGE

LHCI_BUILD_CONTEXT__COMMIT_TIME="${LHCI_BUILD_CONTEXT__COMMIT_TIME:-$(date --iso-8601=seconds)}"
export LHCI_BUILD_CONTEXT__COMMIT_TIME

LHCI_BUILD_CONTEXT__AUTHOR="${LHCI_BUILD_CONTEXT__AUTHOR:-CRON_JOB}"
export LHCI_BUILD_CONTEXT__AUTHOR

LHCI_BUILD_CONTEXT__AVATAR_URL="${LHCI_BUILD_CONTEXT__AVATAR_URL:-https://picsum.photos/200}"
export LHCI_BUILD_CONTEXT__AVATAR_URL

lhci collect --config="$CONFIG_PATH" && lhci upload --config="$CONFIG_PATH"
